required:
  - id
  - name
type: object
properties:
  id:
    type: string
    description: The ID of the field configuration scheme.
  name:
    type: string
    description: The name of the field configuration scheme.
  description:
    type: string
    description: The description of the field configuration scheme.
additionalProperties: false
description: Details of a field configuration scheme.
