required:
  - projectId
type: object
properties:
  fieldConfigurationSchemeId:
    type: string
    description: >-
      The ID of the field configuration scheme. If the field configuration
      scheme ID is `null`, the operation assigns the default field configuration
      scheme.
    writeOnly: true
  projectId:
    type: string
    description: The ID of the project.
    writeOnly: true
additionalProperties: false
description: Associated field configuration scheme and project.
