required:
  - name
type: object
properties:
  name:
    maxLength: 255
    type: string
    description: The name of the field configuration. Must be unique.
    writeOnly: true
  description:
    maxLength: 255
    type: string
    description: The description of the field configuration.
    writeOnly: true
additionalProperties: false
description: Details of a field configuration.
