required:
  - id
  - plan
type: object
properties:
  id:
    type: string
    description: The ID of the application.
    readOnly: true
  plan:
    type: string
    description: The licensing plan.
    readOnly: true
    enum:
      - UNLICENSED
      - FREE
      - PAID
additionalProperties: false
description: Details about a licensed Jira application.
