required:
  - value
type: object
properties:
  value:
    type: string
    description: >-
      Configuration of the rule, as it is stored by the Connect app on the rule
      configuration page.
  disabled:
    type: boolean
    description: 'EXPERIMENTAL: Whether the rule is disabled.'
    default: false
  tag:
    maxLength: 255
    type: string
    description: >-
      EXPERIMENTAL: A tag used to filter rules in [Get workflow transition rule
      configurations](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-workflow-transition-rules/#api-rest-api-3-workflow-rule-config-get).
additionalProperties: false
description: A rule configuration.
