required:
  - name
type: object
properties:
  name:
    maxLength: 255
    type: string
    description: The name of the field configuration scheme. The name must be unique.
    writeOnly: true
  description:
    maxLength: 1024
    type: string
    description: The description of the field configuration scheme.
    writeOnly: true
additionalProperties: false
description: The details of the field configuration scheme.
