put:
  tags:
    - Workflow transition rules
  summary: Delete workflow transition rule configurations
  description: >-
    Deletes workflow transition rules from one or more workflows. These rule
    types are supported:

     *  [post functions](https://developer.atlassian.com/cloud/jira/platform/modules/workflow-post-function/)
     *  [conditions](https://developer.atlassian.com/cloud/jira/platform/modules/workflow-condition/)
     *  [validators](https://developer.atlassian.com/cloud/jira/platform/modules/workflow-validator/)

    Only rules created by the calling Connect app can be deleted.


    **[Permissions](#permissions) required:** Only Connect apps can use this
    operation.
  operationId: deleteWorkflowTransitionRuleConfigurations
  parameters: []
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/WorkflowsWithTransitionRulesDetails.yaml
        example:
          workflows:
            - workflowRuleIds:
                - b4d6cbdc-59f5-11e9-8647-d663bd873d93
                - d663bd873d93-59f5-11e9-8647-b4d6cbdc
                - 11e9-59f5-b4d6cbdc-8647-d663bd873d93
              workflowId:
                draft: false
                name: Internal support workflow
    required: true
  responses:
    '200':
      description: Returned if the request is successful.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/WorkflowTransitionRulesUpdateErrors.yaml
          example: >-
            {"updateResults":[{"workflowId":{"name":"Workflow with one rule not
            updated","draft":false},"ruleUpdateErrors":{"example-rule-id":["The
            rule with this id does not exist:
            example-rule-id"]},"updateErrors":[]},{"workflowId":{"name":"Workflow
            with all rules successfully
            updated","draft":true},"ruleUpdateErrors":{},"updateErrors":[]},{"workflowId":{"name":"Non-existing
            workflow","draft":false},"ruleUpdateErrors":{},"updateErrors":["Workflow
            not found: WorkflowIdBean{name=Non-existing workflow,
            draft=false}"]}]}
    '400':
      description: Returned if the request is invalid.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ErrorCollection.yaml
          example: >-
            {"errors":{},"errorMessages":["Jira Administration permission is
            required to access workflow
            configuration."],"httpStatusCode":{"present":true}}
    '403':
      description: Returned if the caller is not a Connect app.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ErrorCollection.yaml
  deprecated: false
  security:
    - basicAuth: []
  x-atlassian-connect-scope: ADMIN
