get:
  tags:
    - Issue field configurations
  summary: Get all field configuration schemes
  description: >-
    Returns a [paginated](#pagination) list of field configuration schemes.


    Only field configuration schemes used in classic projects are returned.


    **[Permissions](#permissions) required:** *Administer Jira* [global
    permission](https://confluence.atlassian.com/x/x4dKLg).
  operationId: getAllFieldConfigurationSchemes
  parameters:
    - name: startAt
      in: query
      description: >-
        The index of the first item to return in a page of results (page
        offset).
      schema:
        type: integer
        format: int64
        default: 0
    - name: maxResults
      in: query
      description: The maximum number of items to return per page.
      schema:
        type: integer
        format: int32
        default: 50
    - name: id
      in: query
      description: >-
        The list of field configuration scheme IDs. To include multiple IDs,
        provide an ampersand-separated list. For example, `id=10000&id=10001`.
      schema:
        uniqueItems: true
        type: array
        items:
          type: integer
          format: int64
  responses:
    '200':
      description: Returned if the request is successful.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/PageBeanFieldConfigurationScheme.yaml
          example: >-
            {"maxResults":10,"startAt":0,"total":3,"isLast":true,"values":[{"id":"10000","name":"Field
            Configuration Scheme for Bugs","description":"This field
            configuration scheme is for bugs only."},{"id":"10001","name":"Field
            Configuration Scheme for software related
            projects","description":"We can use this one for software
            projects."},{"id":"10002","name":"Field Configuration Scheme for
            Epics","description":"Use this one for Epic issue type."}]}
    '400':
      description: Returned if the request is not valid.
    '401':
      description: Returned if the authentication credentials are incorrect or missing.
    '403':
      description: Returned if the user does not have the necessary permissions.
  deprecated: false
  security:
    - basicAuth: []
    - OAuth2:
        - manage:jira-configuration
  x-atlassian-oauth2-scopes:
    - state: Current
      scheme: OAuth2
      scopes:
        - manage:jira-configuration
    - state: Beta
      scheme: OAuth2
      scopes:
        - read:field-configuration-scheme:jira
  x-atlassian-connect-scope: ADMIN
post:
  tags:
    - Issue field configurations
  summary: Create field configuration scheme
  description: >-
    Creates a field configuration scheme.


    This operation can only create field configuration schemes used in
    company-managed (classic) projects.


    **[Permissions](#permissions) required:** *Administer Jira* [global
    permission](https://confluence.atlassian.com/x/x4dKLg).
  operationId: createFieldConfigurationScheme
  parameters: []
  requestBody:
    description: The details of the field configuration scheme.
    content:
      application/json:
        schema:
          $ref: ../components/schemas/UpdateFieldConfigurationSchemeDetails.yaml
        example:
          name: Field Configuration Scheme for software related projects
          description: We can use this one for software projects.
    required: true
  responses:
    '201':
      description: Returned if the request is successful.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/FieldConfigurationScheme.yaml
          example: >-
            {"id":"10002","name":"Field Configuration Scheme for software
            related projects","description":"We can use this one for software
            projects."}
    '400':
      description: Returned if the request is not valid.
      content:
        application/json:
          example: >-
            {"errorMessages":["A field configuration scheme is using this
            name."],"errors":{}}
    '401':
      description: Returned if the authentication credentials are incorrect or missing.
    '403':
      description: Returned if the user does not have the necessary permissions.
      content:
        application/json:
          example: >-
            {"errorMessages":["Only Jira administrators can access field
            configurations."],"errors":{}}
  deprecated: false
  security:
    - basicAuth: []
    - OAuth2:
        - manage:jira-configuration
  x-atlassian-oauth2-scopes:
    - state: Current
      scheme: OAuth2
      scopes:
        - manage:jira-configuration
    - state: Beta
      scheme: OAuth2
      scopes:
        - write:field-configuration-scheme:jira
        - read:field-configuration-scheme:jira
  x-experimental: true
  x-atlassian-connect-scope: ADMIN
