put:
  tags:
    - Issue field configurations
  summary: Update field configuration scheme
  description: >-
    Updates a field configuration scheme.


    This operation can only update field configuration schemes used in
    company-managed (classic) projects.


    **[Permissions](#permissions) required:** *Administer Jira* [global
    permission](https://confluence.atlassian.com/x/x4dKLg).
  operationId: updateFieldConfigurationScheme
  parameters:
    - name: id
      in: path
      description: The ID of the field configuration scheme.
      required: true
      schema:
        type: integer
        format: int64
  requestBody:
    description: The details of the field configuration scheme.
    content:
      application/json:
        schema:
          $ref: ../components/schemas/UpdateFieldConfigurationSchemeDetails.yaml
        example:
          name: Field Configuration Scheme for software related projects
          description: We can use this one for software projects.
    required: true
  responses:
    '204':
      description: Returned if the request is successful.
      content:
        application/json:
          schema: {}
    '400':
      description: Returned if the request is not valid.
      content:
        application/json:
          example: >-
            {"errorMessages":["A field configuration scheme is using this
            name."],"errors":{}}
    '401':
      description: Returned if the authentication credentials are incorrect or missing.
    '403':
      description: Returned if the user does not have the necessary permissions.
      content:
        application/json:
          example: >-
            {"errorMessages":["Only Jira administrators can access field
            configurations."],"errors":{}}
    '404':
      description: Returned if the field configuration scheme is not found.
      content:
        application/json:
          example: >-
            {"errorMessages":["The field configuration scheme was not
            found."],"errors":{}}
  deprecated: false
  security:
    - basicAuth: []
    - OAuth2:
        - manage:jira-configuration
  x-atlassian-oauth2-scopes:
    - state: Current
      scheme: OAuth2
      scopes:
        - manage:jira-configuration
    - state: Beta
      scheme: OAuth2
      scopes:
        - write:field-configuration-scheme:jira
  x-experimental: true
  x-atlassian-connect-scope: ADMIN
delete:
  tags:
    - Issue field configurations
  summary: Delete field configuration scheme
  description: >-
    Deletes a field configuration scheme.


    This operation can only delete field configuration schemes used in
    company-managed (classic) projects.


    **[Permissions](#permissions) required:** *Administer Jira* [global
    permission](https://confluence.atlassian.com/x/x4dKLg).
  operationId: deleteFieldConfigurationScheme
  parameters:
    - name: id
      in: path
      description: The ID of the field configuration scheme.
      required: true
      schema:
        type: integer
        format: int64
  responses:
    '204':
      description: Returned if the request is successful.
      content:
        application/json:
          schema: {}
    '400':
      description: Returned if the request is not valid.
    '401':
      description: Returned if the authentication credentials are incorrect or missing.
    '403':
      description: Returned if the user does not have the necessary permission.
    '404':
      description: Returned if the field configuration scheme is not found.
  deprecated: false
  security:
    - basicAuth: []
    - OAuth2:
        - manage:jira-configuration
  x-atlassian-oauth2-scopes:
    - state: Current
      scheme: OAuth2
      scopes:
        - manage:jira-configuration
    - state: Beta
      scheme: OAuth2
      scopes:
        - delete:field-configuration-scheme:jira
  x-experimental: true
  x-atlassian-connect-scope: ADMIN
