get:
  tags:
    - Time tracking
  summary: Get all time tracking providers
  description: >-
    Returns all time tracking providers. By default, Jira only has one time
    tracking provider: *JIRA provided time tracking*. However, you can install
    other time tracking providers via apps from the Atlassian Marketplace. For
    more information on time tracking providers, see the documentation for the [
    Time Tracking
    Provider](https://developer.atlassian.com/cloud/jira/platform/modules/time-tracking-provider/)
    module.


    **[Permissions](#permissions) required:** *Administer Jira* [global
    permission](https://confluence.atlassian.com/x/x4dKLg).
  operationId: getAvailableTimeTrackingImplementations
  parameters: []
  responses:
    '200':
      description: Returned if the request is successful.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../components/schemas/TimeTrackingProvider.yaml
          example: >-
            [{"key":"Jira","name":"JIRA provided time
            tracking","url":"/example/config/url"}]
    '401':
      description: Returned if the authentication credentials are incorrect or missing.
    '403':
      description: Returned if the user does not have the necessary permission.
  deprecated: false
  security:
    - basicAuth: []
    - OAuth2:
        - manage:jira-configuration
  x-atlassian-oauth2-scopes:
    - state: Current
      scheme: OAuth2
      scopes:
        - manage:jira-configuration
    - state: Beta
      scheme: OAuth2
      scopes:
        - read:issue.time-tracking:jira
  x-atlassian-connect-scope: READ
