get:
  tags:
    - Time tracking
  summary: Get selected time tracking provider
  description: >-
    Returns the time tracking provider that is currently selected. Note that if
    time tracking is disabled, then a successful but empty response is returned.


    **[Permissions](#permissions) required:** *Administer Jira* [global
    permission](https://confluence.atlassian.com/x/x4dKLg).
  operationId: getSelectedTimeTrackingImplementation
  parameters: []
  responses:
    '200':
      description: Returned if the request is successful and time tracking is enabled.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/TimeTrackingProvider.yaml
          example: >-
            {"key":"Jira","name":"JIRA provided time
            tracking","url":"/example/config/url"}
    '204':
      description: Returned if the request is successful but time tracking is disabled.
      content:
        application/json:
          schema: {}
    '401':
      description: Returned if the authentication credentials are incorrect or missing.
    '403':
      description: Returned if the user does not have the necessary permission.
  deprecated: false
  security:
    - basicAuth: []
    - OAuth2:
        - manage:jira-configuration
  x-atlassian-oauth2-scopes:
    - state: Current
      scheme: OAuth2
      scopes:
        - manage:jira-configuration
    - state: Beta
      scheme: OAuth2
      scopes:
        - read:issue.time-tracking:jira
  x-atlassian-connect-scope: READ
put:
  tags:
    - Time tracking
  summary: Select time tracking provider
  description: >-
    Selects a time tracking provider.


    **[Permissions](#permissions) required:** *Administer Jira* [global
    permission](https://confluence.atlassian.com/x/x4dKLg).
  operationId: selectTimeTrackingImplementation
  parameters: []
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/TimeTrackingProvider.yaml
        example:
          key: Jira
    required: true
  responses:
    '204':
      description: Returned if the request is successful.
      content:
        application/json:
          schema: {}
    '400':
      description: Returned if the time tracking provider is not found.
    '401':
      description: Returned if the authentication credentials are incorrect or missing.
    '403':
      description: Returned if the user does not have the necessary permission.
  deprecated: false
  security:
    - basicAuth: []
    - OAuth2:
        - manage:jira-configuration
  x-atlassian-oauth2-scopes:
    - state: Current
      scheme: OAuth2
      scopes:
        - manage:jira-configuration
    - state: Beta
      scheme: OAuth2
      scopes:
        - write:issue.time-tracking:jira
  x-atlassian-connect-scope: ADMIN
