get:
  tags:
    - Jira settings
  summary: Get application property
  description: >-
    Returns all application properties or an application property.


    If you specify a value for the `key` parameter, then an application property
    is returned as an object (not in an array). Otherwise, an array of all
    editable application properties is returned. See [Set application
    property](#api-rest-api-2-application-properties-id-put) for descriptions of
    editable properties.


    **[Permissions](#permissions) required:** *Administer Jira* [global
    permission](https://confluence.atlassian.com/x/x4dKLg).
  operationId: getApplicationProperty
  parameters:
    - name: key
      in: query
      description: The key of the application property.
      schema:
        type: string
    - name: permissionLevel
      in: query
      description: The permission level of all items being returned in the list.
      schema:
        type: string
    - name: keyFilter
      in: query
      description: >-
        When a `key` isn't provided, this filters the list of results by the
        application property `key` using a regular expression. For example,
        using `jira.lf.*` will return all application properties with keys that
        start with *jira.lf.*.
      schema:
        type: string
  responses:
    '200':
      description: Returned if the request is successful.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../components/schemas/ApplicationProperty.yaml
          example: >-
            [{"id":"jira.home","key":"jira.home","value":"/var/jira/jira-home","name":"jira.home","desc":"Jira
            home
            directory","type":"string","defaultValue":""},{"id":"jira.clone.prefix","key":"jira.clone.prefix","value":"CLONE
            -","name":"The prefix added to the Summary field of cloned
            issues","type":"string","defaultValue":"CLONE -"}]
    '401':
      description: Returned if the authentication credentials are incorrect or missing.
    '404':
      description: >-
        Returned if the application property is not found or the user does not
        have permission to view it.
  deprecated: false
  security:
    - basicAuth: []
    - OAuth2:
        - manage:jira-configuration
  x-atlassian-oauth2-scopes:
    - state: Current
      scheme: OAuth2
      scopes:
        - manage:jira-configuration
    - state: Beta
      scheme: OAuth2
      scopes:
        - read:instance-configuration:jira
  x-atlassian-connect-scope: ADMIN
