get:
  tags:
    - Issue field configurations
  summary: Get field configuration items
  description: >-
    Returns a [paginated](#pagination) list of all fields for a configuration.


    Only the fields from configurations used in company-managed (classic)
    projects are returned.


    **[Permissions](#permissions) required:** *Administer Jira* [global
    permission](https://confluence.atlassian.com/x/x4dKLg).
  operationId: getFieldConfigurationItems
  parameters:
    - name: id
      in: path
      description: The ID of the field configuration.
      required: true
      schema:
        type: integer
        format: int64
    - name: startAt
      in: query
      description: >-
        The index of the first item to return in a page of results (page
        offset).
      schema:
        type: integer
        format: int64
        default: 0
    - name: maxResults
      in: query
      description: The maximum number of items to return per page.
      schema:
        type: integer
        format: int32
        default: 50
  responses:
    '200':
      description: Returned if the request is successful.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/PageBeanFieldConfigurationItem.yaml
          example: >-
            {"maxResults":50,"startAt":0,"total":2,"isLast":true,"values":[{"id":"environment","description":"For
            example operating system, software platform and/or hardware
            specifications (include as appropriate for the
            issue).","isHidden":false,"isRequired":false},{"id":"description","isHidden":false,"isRequired":false}]}
    '401':
      description: Returned if the authentication credentials are incorrect or missing.
    '403':
      description: Returned if the user does not have the necessary permission.
    '404':
      description: Returned if the field configuration is not found.
  deprecated: false
  security:
    - basicAuth: []
    - OAuth2:
        - manage:jira-configuration
  x-atlassian-oauth2-scopes:
    - state: Current
      scheme: OAuth2
      scopes:
        - manage:jira-configuration
    - state: Beta
      scheme: OAuth2
      scopes:
        - read:field-configuration:jira
  x-atlassian-connect-scope: ADMIN
put:
  tags:
    - Issue field configurations
  summary: Update field configuration items
  description: >-
    Updates fields in a field configuration. The properties of the field
    configuration fields provided override the existing values.


    This operation can only update field configurations used in company-managed
    (classic) projects.


    The operation can set the renderer for text fields to the default text
    renderer (`text-renderer`) or wiki style renderer (`wiki-renderer`).
    However, the renderer cannot be updated for fields using the autocomplete
    renderer (`autocomplete-renderer`).


    **[Permissions](#permissions) required:** *Administer Jira* [global
    permission](https://confluence.atlassian.com/x/x4dKLg).
  operationId: updateFieldConfigurationItems
  parameters:
    - name: id
      in: path
      description: The ID of the field configuration.
      required: true
      schema:
        type: integer
        format: int64
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/FieldConfigurationItemsDetails.yaml
        example:
          fieldConfigurationItems:
            - description: The new description of this item.
              id: customfield_10012
              isHidden: false
            - isRequired: true
              id: customfield_10011
            - isRequired: false
              renderer: wiki-renderer
              description: Another new description.
              id: customfield_10010
              isHidden: false
    required: true
  responses:
    '204':
      description: Returned if the request is successful.
      content:
        application/json:
          schema: {}
    '400':
      description: Returned if the request is not valid.
    '401':
      description: Returned if the authentication credentials are incorrect or missing.
    '403':
      description: Returned if the user does not have the necessary permission.
    '404':
      description: Returned if the field configuration is not found.
  deprecated: false
  security:
    - basicAuth: []
    - OAuth2:
        - manage:jira-configuration
  x-atlassian-oauth2-scopes:
    - state: Current
      scheme: OAuth2
      scopes:
        - manage:jira-configuration
    - state: Beta
      scheme: OAuth2
      scopes:
        - write:field-configuration:jira
  x-experimental: true
  x-atlassian-connect-scope: ADMIN
