get:
  tags:
    - Issue navigator settings
  summary: Get issue navigator default columns
  description: >-
    Returns the default issue navigator columns.


    **[Permissions](#permissions) required:** *Administer Jira* [global
    permission](https://confluence.atlassian.com/x/x4dKLg).
  operationId: getIssueNavigatorDefaultColumns
  parameters: []
  responses:
    '200':
      description: Returned if the request is successful.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../components/schemas/ColumnItem.yaml
          example: >-
            [{"label":"Key","value":"issuekey"},{"label":"Summary","value":"summary"}]
    '401':
      description: Returned if the authentication credentials are incorrect or missing.
    '403':
      description: Returned if the user does not have the necessary permission.
  deprecated: false
  security:
    - basicAuth: []
  x-atlassian-connect-scope: INACCESSIBLE
put:
  tags:
    - Issue navigator settings
  summary: Set issue navigator default columns
  description: >-
    Sets the default issue navigator columns.


    The `columns` parameter accepts a navigable field value and is expressed as
    HTML form data. To specify multiple columns, pass multiple `columns`
    parameters. For example, in curl:


    `curl -X PUT -d columns=summary -d columns=description
    https://your-domain.atlassian.net/rest/api/2/settings/columns`


    If no column details are sent, then all default columns are removed.


    A navigable field is one that can be used as a column on the issue
    navigator. Find details of navigable issue columns using [Get
    fields](#api-rest-api-2-field-get).


    **[Permissions](#permissions) required:** *Administer Jira* [global
    permission](https://confluence.atlassian.com/x/x4dKLg).
  operationId: setIssueNavigatorDefaultColumns
  parameters: []
  requestBody:
    description: A navigable field value.
    content:
      '*/*':
        schema:
          type: array
          items:
            type: string
      multipart/form-data:
        schema:
          type: array
          items:
            type: string
  responses:
    '200':
      description: Returned if the request is successful.
      content:
        application/json:
          schema: {}
    '400':
      description: Returned if invalid parameters are passed.
    '401':
      description: Returned if the authentication credentials are incorrect or missing.
    '403':
      description: Returned if the user does not have the necessary permission.
    '404':
      description: Returned if a navigable field value is not found.
  deprecated: false
  security:
    - basicAuth: []
  x-atlassian-connect-scope: INACCESSIBLE
