put:
  tags:
    - Issue field configurations
  summary: Update field configuration
  description: >-
    Updates a field configuration. The name and the description provided in the
    request override the existing values.


    This operation can only update configurations used in company-managed
    (classic) projects.


    **[Permissions](#permissions) required:** *Administer Jira* [global
    permission](https://confluence.atlassian.com/x/x4dKLg).
  operationId: updateFieldConfiguration
  parameters:
    - name: id
      in: path
      description: The ID of the field configuration.
      required: true
      schema:
        type: integer
        format: int64
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/FieldConfigurationDetails.yaml
        example:
          name: My Modified Field Configuration
          description: A brand new description
    required: true
  responses:
    '204':
      description: Returned if the request is successful.
      content:
        application/json:
          schema: {}
    '400':
      description: Returned if the request is not valid.
    '401':
      description: Returned if the authentication credentials are incorrect or missing.
    '403':
      description: Returned if the user does not have the necessary permission.
    '404':
      description: Returned if the field configuration is not found.
  deprecated: false
  security:
    - basicAuth: []
    - OAuth2:
        - manage:jira-configuration
  x-atlassian-oauth2-scopes:
    - state: Current
      scheme: OAuth2
      scopes:
        - manage:jira-configuration
    - state: Beta
      scheme: OAuth2
      scopes:
        - write:field-configuration:jira
  x-experimental: true
  x-atlassian-connect-scope: ADMIN
delete:
  tags:
    - Issue field configurations
  summary: Delete field configuration
  description: >-
    Deletes a field configuration.


    This operation can only delete configurations used in company-managed
    (classic) projects.


    **[Permissions](#permissions) required:** *Administer Jira* [global
    permission](https://confluence.atlassian.com/x/x4dKLg).
  operationId: deleteFieldConfiguration
  parameters:
    - name: id
      in: path
      description: The ID of the field configuration.
      required: true
      schema:
        type: integer
        format: int64
  responses:
    '204':
      description: Returned if the request is successful.
      content:
        application/json:
          schema: {}
    '400':
      description: Returned if the request is not valid.
    '401':
      description: Returned if the authentication credentials are incorrect or missing.
    '403':
      description: Returned if the user does not have the necessary permission.
    '404':
      description: Returned if the field configuration is not found.
  deprecated: false
  security:
    - basicAuth: []
    - OAuth2:
        - manage:jira-configuration
  x-atlassian-oauth2-scopes:
    - state: Current
      scheme: OAuth2
      scopes:
        - manage:jira-configuration
    - state: Beta
      scheme: OAuth2
      scopes:
        - delete:field-configuration:jira
  x-experimental: true
  x-atlassian-connect-scope: ADMIN
