get:
  tags:
    - Time tracking
  summary: Get time tracking settings
  description: >-
    Returns the time tracking settings. This includes settings such as the time
    format, default time unit, and others. For more information, see
    [Configuring time tracking](https://confluence.atlassian.com/x/qoXKM).


    **[Permissions](#permissions) required:** *Administer Jira* [global
    permission](https://confluence.atlassian.com/x/x4dKLg).
  operationId: getSharedTimeTrackingConfiguration
  parameters: []
  responses:
    '200':
      description: Returned if the request is successful.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/TimeTrackingConfiguration.yaml
          example: >-
            {"workingHoursPerDay":7.6,"workingDaysPerWeek":5.5,"timeFormat":"pretty","defaultUnit":"hour"}
    '401':
      description: Returned if the authentication credentials are incorrect or missing.
    '403':
      description: Returned if the user does not have the necessary permission.
  deprecated: false
  security:
    - basicAuth: []
    - OAuth2:
        - manage:jira-configuration
  x-atlassian-oauth2-scopes:
    - state: Current
      scheme: OAuth2
      scopes:
        - manage:jira-configuration
    - state: Beta
      scheme: OAuth2
      scopes:
        - read:issue.time-tracking:jira
  x-atlassian-connect-scope: READ
put:
  tags:
    - Time tracking
  summary: Set time tracking settings
  description: >-
    Sets the time tracking settings.


    **[Permissions](#permissions) required:** *Administer Jira* [global
    permission](https://confluence.atlassian.com/x/x4dKLg).
  operationId: setSharedTimeTrackingConfiguration
  parameters: []
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/TimeTrackingConfiguration.yaml
        example:
          defaultUnit: hour
          workingHoursPerDay: 7.6
          workingDaysPerWeek: 5.5
          timeFormat: pretty
    required: true
  responses:
    '200':
      description: Returned if the request is successful.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/TimeTrackingConfiguration.yaml
          example: >-
            {"workingHoursPerDay":7.6,"workingDaysPerWeek":5.5,"timeFormat":"pretty","defaultUnit":"hour"}
    '400':
      description: Returned if the request object is invalid.
    '401':
      description: Returned if the authentication credentials are incorrect or missing.
    '403':
      description: Returned if the user does not have the necessary permission.
  deprecated: false
  security:
    - basicAuth: []
    - OAuth2:
        - manage:jira-configuration
  x-atlassian-oauth2-scopes:
    - state: Current
      scheme: OAuth2
      scopes:
        - manage:jira-configuration
    - state: Beta
      scheme: OAuth2
      scopes:
        - write:issue.time-tracking:jira
        - read:issue.time-tracking:jira
  x-atlassian-connect-scope: ADMIN
