get:
  tags:
    - Application roles
  summary: Get application role
  description: >-
    Returns an application role.


    **[Permissions](#permissions) required:** *Administer Jira* [global
    permission](https://confluence.atlassian.com/x/x4dKLg).
  operationId: getApplicationRole
  parameters:
    - name: key
      in: path
      description: >-
        The key of the application role. Use the [Get all application
        roles](#api-rest-api-2-applicationrole-get) operation to get the key for
        each application role.
      required: true
      schema:
        type: string
        example: jira-software
      x-showInExample: 'true'
  responses:
    '200':
      description: Returned if the request is successful.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApplicationRole.yaml
          example: >-
            {"key":"jira-software","groups":["jira-software-users","jira-testers"],"groupDetails":[{"name":"jira-testers","groupId":"42c8955c-63d7-42c8-9520-63d7aca0625","self":"https://your-domain.atlassian.net/rest/api/2/group?groupId=42c8955c-63d7-42c8-9520-63d7aca0625"},{"name":"jira-software-users","groupId":"276f955c-63d7-42c8-9520-92d01dca0625","self":"https://your-domain.atlassian.net/rest/api/2/group?groupId=276f955c-63d7-42c8-9520-92d01dca0625"}],"name":"Jira
            Software","defaultGroups":["jira-software-users"],"defaultGroupsDetails":[{"name":"jira-software-users","groupId":"276f955c-63d7-42c8-9520-92d01dca0625","self":"https://your-domain.atlassian.net/rest/api/2/group?groupId=276f955c-63d7-42c8-9520-92d01dca0625"}],"selectedByDefault":false,"defined":false,"numberOfSeats":10,"remainingSeats":5,"userCount":5,"userCountDescription":"5
            developers","hasUnlimitedSeats":false,"platform":false}
    '401':
      description: Returned if the authentication credentials are incorrect or missing.
    '403':
      description: Returned if the user is not an administrator.
    '404':
      description: Returned if the role is not found.
  deprecated: false
  security:
    - basicAuth: []
  x-atlassian-connect-scope: INACCESSIBLE
